title: Taewhei Kim's Blog
email: xoghl1124@gmail.com
description: >- 
  백엔드 개발자 김태회의 블로그입니다.
baseurl: "" 
url: "https://f-los.github.io" 
github_username:  F-los

# Build settings
theme: jekyll-theme-chirpy
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap

author:
name: TaeWhei Kim
email: your.email@example.com
github: F-los
linkedin: your-linkedin


paginate: 10
paginate_path: "/blog/page:num/"