# 사이트 기본 정보
title: "Taewhei Kim's Blog"
description: >-
  백엔드 개발자 김태회의 블로그입니다.
baseurl: ""
url: "https://f-los.github.io"
lang: ko
timezone: Asia/Seoul

# GitHub Pages 원격 테마(Chirpy) - 일시적으로 비활성화
# remote_theme: cotes2020/jekyll-theme-chirpy
theme: minima

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 작성자 정보
author:
  name: "TaeWhei Kim"
  email: "xoghl1124@example.com"
  github: "F-los"
  linkedin: "your-linkedin"

# Github 계정(필요 시)
github_username: "F-los"

# 블로그 페이징
paginate: 10
paginate_path: "/blog/page:num/"
